### ISSUE TITLE
Can't build on FreeBSD

### ISSUE THREAD

**Issue by igorzigorz** [Edrusb/libthreadar#1]
Hi,

Can't build on FreeBSD 

exceptions.cpp:68:8: error: cannot initialize a variable of type 'char *' with
      an rvalue of type 'int'
        char *val = strerror_r(error_code, buffer, MSGSIZE);

Please, make this code *BSD compatible.

**Comment by Edrusb** [comment]
Sorry missed seing your message! will check how to fix that

**Comment by Edrusb** [comment]
You should now build libthreadar on FreeBSD starting with release 1.3.3
Thanks for feedback and sorry for the long delay solving this issue (seems I missed the notification when you open this issue).
